## 1️⃣ Introduction to NumPy

NumPy (Numerical Python) is a library used for numerical computing in Python. It provides fast and memory-efficient arrays and mathematical functions.

In [ ]:
import numpy as np
print("numpy imported successfully")

numpy imported successfully


In [3]:
print("numpy version-")
print(np.__version__)

numpy version-
1.26.4


## 2️⃣ NumPy N-dimensional Arrays (1D, 2D, 3D)

NumPy arrays can be 1D, 2D, or 3D. They are more efficient than Python lists.

In [ ]:
# Creating numpy arrays of different dimensions

arr1D=np.array([1,2,3,4])
print("1D Array\n ",arr1D)


arr2D=np.array([[1,2,3,4],[1,2,3,4]])
print("2D array\n ",arr2D)


arr3D=np.array([[[1,2,3],[34,5,6]],[[2,3,4],[3,4,6]]])
print("3D array\n ",arr3D)

1d Array
  [1 2 3 4]
2d array
  [[1 2 3 4]
 [1 2 3 4]]
3d array
  [[[ 1  2  3]
  [34  5  6]]

 [[ 2  3  4]
  [ 3  4  6]]]


## 3️⃣ Functions to Create Arrays

NumPy provides multiple functions to create arrays efficiently.

| Function       | Argument Type      | Example   |
|----------------|--------------------|-----------|
| `np.zeros()`   | Tuple for shape    | `(3, 3)`  |
| `np.ones()`    | Tuple for shape    | `(2, 3)`  |
| *Note:* Only `array`, `ones`, `zeros`, `empty` accept a tuple of arguments |  |  |
| `np.identity()`| Single integer     | `2`       |

In [6]:
# Creating numpy arrays with different methods

# Creating array filled with zeros
zeros_array=np.zeros((3,3))
print("array filled with zeros\n ",zeros_array)


# Creating array filled with ones
ones_array=np.ones((2,3))
print("array filled with ones\n ",ones_array)


# Creating array filled with random values
random_array=np.random.rand(4,4)
print('array filled with random values\n ',random_array)


# Creating arrays with specific values
identity_matrix=np.identity(2)
print("identity matrix\n ",identity_matrix)


# Creating arrays with specific values
arr = np.full((2, 3), 7)
print("array full of 7\n ",arr)


# Creating arrays with specific values
empty_array=np.empty((2,3))
print("empty arrey\n ",empty_array)


# Creating arrays with specific values
arrange_array = np.arange(1, 10, 4) # Create an array from 1 to 10 with step 4
print("arranged array\n ",arrange_array)  

array filled with zeros
  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
array filled with ones
  [[1. 1. 1.]
 [1. 1. 1.]]
array filled with random values
  [[0.94434027 0.07152819 0.8352669  0.7832272 ]
 [0.87209777 0.90888562 0.27542318 0.29116798]
 [0.88065063 0.08507801 0.97638512 0.75054192]
 [0.79937807 0.0418297  0.05016754 0.86195757]]
identity matrix
  [[1. 0.]
 [0. 1.]]
array full of 7
  [[7 7 7]
 [7 7 7]]
empty arrey
  [[1. 1. 1.]
 [1. 1. 1.]]
arranged array
  [1 5 9]


## 4️⃣ Combining Arrays

We can combine multiple arrays using concatenation.

In [16]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a,b))

print('concatenated array\n ',c)

concatenated array
  [1 2 3 4 5 6]


## 5️⃣ Indexing, Slicing & Reshaping

 - 🔹np.sum() works on anything array-like.

 - 🔹arr.sum() only works on NumPy arrays (or pandas Series, etc.)

In [17]:
arr = np.array([10, 20, 30, 40, 50])
print('First Element:', arr[0])
print('Last 3 Elements:', arr[-3:])
reshaped = arr.reshape(5,1)
print('Reshaped Array:\n', reshaped)

First Element: 10
Last 3 Elements: [30 40 50]
Reshaped Array:
 [[10]
 [20]
 [30]
 [40]
 [50]]


convert one 2d array into another 2d array

In [23]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=a.reshape(9,1)
print("reshaped array\n ",b)

reshaped array
  [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


## 6️⃣ String Indexing & Slicing

In [28]:
text = 'NumPy Library'
print('First Character:', text[0])
print('Slice:', text[0:5])
print('Reverse:', text[::-1])

First Character: N
Slice: NumPy
Reverse: yrarbiL yPmuN


## 7️⃣ Operations on Arrays (Arithmetic & Logical)

In [7]:
# Create two sample numpy arrays
a = np.array([10, 20, 30, 40, 50])
b = np.array([1, 2, 3, 4, 5])

print("Array a:", a)
print("Array b:", b)

# Arithmetic operations
print("\n--- Arithmetic Operations using NumPy methods ---")
print("Addition (a + b):", np.add(a, b))
print("Subtraction (a - b):", np.subtract(a, b))
print("Multiplication (a * b):", np.multiply(a, b))
print("Division (a / b):", np.divide(a, b))
print("Power (a ** 2):", np.power(a, 2))
print("Modulus (a % 3):", np.mod(a, 3))
print("square root of (a^2): ",np.sqrt(a))

Array a: [10 20 30 40 50]
Array b: [1 2 3 4 5]

--- Arithmetic Operations using NumPy methods ---
Addition (a + b): [11 22 33 44 55]
Subtraction (a - b): [ 9 18 27 36 45]
Multiplication (a * b): [ 10  40  90 160 250]
Division (a / b): [10. 10. 10. 10. 10.]
Power (a ** 2): [ 100  400  900 1600 2500]
Modulus (a % 3): [1 2 0 1 2]
square root of (a^2):  [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


## 8️⃣ Statistical operations on array

In [ ]:
# Statistical operations on array a
print("\n--- Statistical Operations on array a ---")
print("Sum:", np.sum(a))
print("Mean:", np.mean(a))
print("Median:", np.median(a))
print("Standard Deviation:", np.std(a))
print("Variance:", np.var(a))
print("Minimum:", np.min(a))
print("Maximum:", np.max(a))

## 9️⃣ Sort and Unique

In [8]:
a = np.array([[1, 2,4], [3, 4,6]])

# Example array 'b'
b = np.array([9, 3, 6, 1])
print("sorted array\n ",np.sort(b))  # Sorts the array: [1 3 6 9]

# Unique values in arrange_array
print("unique elements from the array\n ",np.unique(a))  # Output: [1 5 9]

sorted array
  [1 3 6 9]
unique elements from the array
  [1 2 3 4 6]


## 🔟 Numpy Array atributes

properties alwyas start with the array name

In [9]:
# Create a sample NumPy array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Retrieve and display array properties
print("Array:")
print(arr)

print("\nProperties of the array:")
print(f"Shape: {arr.shape}")             # Dimensions (rows, columns)
print(f"Size: {arr.size}")               # Total number of elements
print(f"Number of dimensions (ndim): {arr.ndim}")
print(f"Data type (dtype): {arr.dtype}") # Data type of elements
print(f"Item size (itemsize): {arr.itemsize} bytes") # Size of each element
print(f"Total bytes (nbytes): {arr.nbytes}") # Total memory in bytes
print(f"Transpose np.transpose(arr):\n{arr.T}")            # Transposed version of the array
print(f"Flat array: {arr.flatten()}")    # Flattened version of the array

Array:
[[1 2 3]
 [4 5 6]]

Properties of the array:
Shape: (2, 3)
Size: 6
Number of dimensions (ndim): 2
Data type (dtype): int32
Item size (itemsize): 4 bytes
Total bytes (nbytes): 24
Transpose np.transpose(arr):
[[1 4]
 [2 5]
 [3 6]]
Flat array: [1 2 3 4 5 6]
